### ISSUE TITLE
git log alias

### ISSUE THREAD

**Issue by CdrMarks** [greg-1-anderson/shell-scripts#5]
Hey Greg,

Did I recall you had an alias named `gl` that would show you a compact view from `git log`?  If so, would you mind adding it?

Ryan

**Comment by greg-1-anderson** [comment]
👋 

I moved all of my git aliases to [g1a/git-bashrc](https://github.com/g1a/git-bashrc), and the fd scripts to [g1a/fd](https://github.com/g1a/fd).

Note that these projects will be automatically installed if you run `source install`.
